version: '3'
services:
  app:
    image: vuepress-flychat
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - username=${USERNAME}
        - password=${PASSWORD}
        - repo=${REPO}
        - domain=${DOMAIN}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./docs:/app/docs
    restart: unless-stopped
    ports:
       - 8080:8080